require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'node_modules/**/*'

# Allow longer lines in certain files
Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/initializers/devise.rb'

# Increase method length limit for migrations and specs
Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'db/migrate/*'

# Allow larger blocks in specs and configs
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'
    - 'lib/tasks/**/*'
  Max: 30

# Increase complexity thresholds slightly
Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

# RSpec specific configurations
RSpec/NestedGroups:
  Max: 4

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/ExampleLength:
  Max: 10

# Factory Bot configurations
FactoryBot/CreateList:
  Enabled: true

# Rails specific configurations
Rails/SkipsModelValidations:
  Exclude:
    - 'spec/**/*'

Rails/BulkChangeTable:
  Exclude:
    - 'db/migrate/*'

Style/Documentation:
  Enabled: true
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'db/migrate/*' 